### ISSUE TITLE
Jatoms component not complete? Didn't get like Multidaytour website

### ISSUE THREAD

**Issue by ebardos** [SeptdirWorkshop/JAtomS#3]
i have install Jatoms component but it didnt look like multidaytour demo website at all. How to get the function and layout same as multidaytour demo website e.g. tour program, Seat availability like multidaytour.ru (please check the attached screenshot)
![to-multi-day-tour](https://user-images.githubusercontent.com/51253892/58743336-f5ad9a00-8461-11e9-915e-8ba002264c1e.jpg)

**Comment by ebardos** [comment]
all i get after the installation is like the screenshot i attached below
![to-multi-day-tour-current-view-after-installation](https://user-images.githubusercontent.com/51253892/58743362-6d7bc480-8462-11e9-9512-9b626853c587.jpg)

**Comment by ebardos** [comment]
my website is https://www.bktravel.asia/

Thanks

**Comment by Septdir** [comment]
@ebardos 

All functions shown on the multidaytour website are already available in the component.

First you need to create an account in the atom-s service and create a showcase for tours there.
At the moment, the service is only available in Russian, but as far as I know in the coming days, English will appear.
Then create a storefront on your site and indicate in it the api key from atom's.
Tours will be obtained from the system automatically.

On Multidaytour show JAtomS Professional.
In terms of functions, it is no different, but the standard version has a more simplified design.

![Standart](https://user-images.githubusercontent.com/18382023/58747192-6bb8fd80-8470-11e9-8c85-3ad40b754bb6.png)

If you want to see how the professional version is arranged, including in the control panel, here is a demo site.

Site
https://jatoms.septdir.com/

Control Panel
https://jatoms.septdir.com/administrator/
Login: `demo_en`
Password: `demo_en`

**Comment by ebardos** [comment]
Hi Igor,

thanks for your reply. I'm looking forward to use your component especially the pro version.

i have registered at atom-s.com and now waiting for your approval.

referring to your reply quoted 
**"At the moment, the service is only available in Russian, but as far as I know in the coming days, English will appear."**
Does this means that only tour places located in Russia will be listed?

If you're agree i can be your testing site for user out of Russia. And if you're agree i can market your components to tours agency in my country.

Thanks

**Comment by atom-system** [comment]
Hello Ebardos!
We will be happy to test and develop our system for your needs.
Details i'll send by e-mail.

Atom-S team
